---
title: "Barometric Correction Function Development"
author: "Simon Marks"
date: "7/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(lubridate)
library(data.table)

```

Barometric Correction Function

Written based off this resource from Onset: link[https://www.onsetcomp.com/support/tech-note/barometric-compensation-method/]

```{r}

barometric_datafile_correction <- function(logger.data, baro.data) {
  
  colnames(logger.data) <- c("Date", "total.pressure_psi", "temp.ref_F")
  colnames(baro.data) <- c("Date", "baro.pressure_psi", "baro.temp_F")
  
    logger.dt <- logger.data %>%
      filter(!is.na(Date),
             !is.na(total.pressure_psi), !is.na(temp.ref_F)) %>%
      data.table(key = 'Date')
    
    baro.dt <- data.table(filter(baro.data, !is.na(Date), 
                                 !is.na(baro.pressure_psi), !is.na(baro.temp_F)),
                          key = 'Date')
    
    logger.baro.dt <- baro.dt[logger.dt, roll = 'nearest']
    
    logger.baro.dt <- logger.baro.dt %>%
      dplyr::mutate(water.pressure_psi = total.pressure_psi - baro.pressure_psi) %>%
      dplyr::select(-baro.temp_F)
    
    level.conversion <- logger.baro.dt %>% 
      # convert temperature of water logger at reference time to deg c for density computation
      dplyr::mutate(temp.ref_C = (temp.ref_F - 32) * (5/9)) %>% 
      # Compute density of water at reference time (lb/ft^3)
      dplyr::mutate(h2o.density = ((999.83952 + (16.945176 * temp.ref_C) - (7.9870401 * 10^-3 * temp.ref_C^2) - (46.170461 * 10^-6 * temp.ref_C^3) + (105.56302 * 10^-9 * temp.ref_C^4) - (280.54253 * 10^-12 * temp.ref_C^5))/(1 + (16.879850 * 10^-3 * temp.ref_C))) * 0.0624279606) %>%
      # compute water level above sensor in ft.
      dplyr::mutate(water.level.above.sensor = round(((water.pressure_psi * 144) / h2o.density), digits = 3)) %>% 
      dplyr::select(-h2o.density, -water.pressure_psi, -temp.ref_C)
    
    if(min(logger.dt$Date) < min(baro.dt$Date) || max(logger.dt$Date) > max(baro.dt$Date))
    warning(sprintf('URGENT: Time range for logger data (%s - %s) is not contained within time range for baro data (%s - %s). Data will be incorrectly compensated.', format(min(logger.dt$Date), '%Y-%m-%d %H:%M'), format(max(logger.dt$Date), '%Y-%m-%d %H:%M'), format(min(baro.dt$Date), '%Y-%m-%d %H:%M'), format(max(baro.dt$Date), '%Y-%m-%d %H:%M')))
  
    return(level.conversion)
  
}

```

