---
title: "RC_wells_dataexplore"
author: "Simon Marks"
date: "10/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(openair)
```

## Compiled Data

```{r}

RC_wells_Aug2020 <- readr::read_csv("RC_Wells_Aug2020/raw/compiledwells_RC_Aug2020.csv", col_types = cols(Date = col_character(), .default = col_double())) %>% 
  dplyr::mutate(Date = as.POSIXct(Date, tz = "UTC"))

plumas_corp_wells <- readr::read_csv("Plumas_Corp_Wells/compiledwells_RC_PlumasCorp_Sept2019.csv", col_types = cols(Date = col_character(), .default = col_double())) %>% 
  dplyr::mutate(Date = as.POSIXct(Date, tz = "UTC"))

```

## Plots

```{r}
RC_wells_Aug2020_plots <- RC_wells_Aug2020 %>% 
  select(-starts_with("water")) %>% 
  tidyr::pivot_longer(cols = starts_with("depth"), names_to = "well_id", values_to = "depth_gw") %>% 
  dplyr::mutate(depth_gw = case_when(
    depth_gw < 0 ~ 0,
    TRUE ~ depth_gw
  )) %>% 
  dplyr::mutate(well_id = stringr::str_remove(well_id, "depth.gw_ft_")) %>% 
  dplyr::mutate(well_id = as.factor(well_id))

plumas_wells_plots <- plumas_corp_wells %>% 
  select(-starts_with("water")) %>% 
  tidyr::pivot_longer(cols = starts_with("depth"), names_to = "well_id", values_to = "depth_gw") %>% 
  dplyr::mutate(depth_gw = case_when(
    depth_gw < 0 ~ 0,
    TRUE ~ depth_gw
  )) %>% 
  dplyr::mutate(well_id = stringr::str_remove(well_id, "depth.gw_ft_")) %>% 
  dplyr::mutate(well_id = as.factor(well_id))
```

```{r}

## RCW6

# Data present 2019-05-30 15:00:00 to 2020-8-17
# Need to remove data on July 9- this was day slug test was done

RC_wells_Aug2020_plots %>% 
  dplyr::filter(well_id == "RCW6") %>%
  # dplyr::filter(Date > as.POSIXct("2019-9-25 00:00:00", tz = "UTC") & Date < as.POSIXct("2019-9-30 00:00:00", tz = "UTC")) %>% 
  ggplot(aes(x = Date, y = depth_gw)) +
  geom_line() +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "2 month")

## RCW3

# Data present 2019-05-30 13:30:00 to 2019-12-16 02:30:00 (battery died powering system)
# 2020-04-25 10:30:00 to 2020-8-17

RC_wells_Aug2020_plots %>% 
  dplyr::filter(well_id == "RCW3") %>%
  dplyr::filter(Date > as.POSIXct("2019-7-15 00:00:00", tz = "UTC") & Date < as.POSIXct("2019-7-30 00:00:00", tz = "UTC")) %>% 
  ggplot(aes(x = Date, y = depth_gw)) +
  geom_line() +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "4 day")

## RCW2

# Data present 2019-09-03 11:00:00 to 2020-8-17
# water table only present between mid-April and early May
# week of 2020-04-13 to 2020-04-20 is when the water table is closest to surface

RC_wells_Aug2020_plots %>% 
  dplyr::filter(well_id == "RCW2") %>%
  dplyr::filter(Date > as.POSIXct("2020-4-13 00:00:00", tz = "UTC") & Date < as.POSIXct("2020-4-16 00:00:00", tz = "UTC")) %>% 
  ggplot(aes(x = Date, y = depth_gw)) +
  geom_line() +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "1 day")

## RCW1

# Data present 2019-05-31 07:30:00 to 2019-10-21 17:30:00 (problems with instrument)
# Data present

RC_wells_Aug2020_plots %>% 
  dplyr::filter(well_id == "RCW1") %>%
  # dplyr::filter(Date > as.POSIXct("2019-6-15 00:00:00", tz = "UTC") & Date < as.POSIXct("2019-6-20 00:00:00", tz = "UTC")) %>% 
  ggplot(aes(x = Date, y = depth_gw)) +
  geom_line() +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "2 month")

## RCW3P and RCW4P

# good looking diurnal pattern from groundwater data at Plumas wells, probably because of instrument quality

plumas_wells_plots %>% 
  dplyr::filter(well_id == "RCW3P") %>%
  dplyr::filter(Date > as.POSIXct("2019-9-25 00:00:00", tz = "UTC") & Date < as.POSIXct("2019-9-30 00:00:00", tz = "UTC")) %>% 
  ggplot(aes(x = Date, y = depth_gw)) +
  geom_line() +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "1 day")

plumas_wells_plots %>% 
  dplyr::filter(well_id == "RCW4P") %>%
  dplyr::filter(Date > as.POSIXct("2019-9-25 00:00:00", tz = "UTC") & Date < as.POSIXct("2019-9-30 00:00:00", tz = "UTC")) %>% 
  ggplot(aes(x = Date, y = depth_gw)) +
  geom_line() +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "1 day")

```


```{r}
RC_wells_Aug2020_plots %>% 
  dplyr::filter(well_id == "RCW2") %>%
  dplyr::filter(Date > as.POSIXct("2020-4-17 00:00:00", tz = "UTC") & Date < as.POSIXct("2020-4-20 00:00:00", tz = "UTC")) %>% 
  dplyr::rename(date = Date) %>% 
  dplyr::select(-well_id) %>% 
  # openair::timeAverage(avg.time = "2 hour") %>% 
  ggplot(aes(x = date, y = depth_gw)) +
  geom_line() +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "1 day")
```

